name = "products-reactrouterv7-cloudflare"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Production environment
[env.production]
name = "products-reactrouterv7-cloudflare"

# Preview environment (for branch deployments)
[env.preview]
name = "products-reactrouterv7-cloudflare-preview"

